name:                serverless-haskell
category:            AWS, Cloud, Network
maintainer:          akotlyarov@seek.com.au
version:             '0.0.4'
github:              seek-oss/serverless-haskell
license:             MIT
synopsis:            Deploying Haskell code onto AWS Lambda using Serverless
description:         Utilities to help process the events from AWS Lambda when deployed with the serverless-haskell plugin.
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-casing
  - amazonka-core
  - amazonka-kinesis
  - amazonka-s3
  - bytestring
  - lens
  - text
  - time
  - unix
  - unordered-containers

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - serverless-haskell
      - hspec
      - hspec-discover
      - raw-strings-qq
