name:                serverless-haskell
category:            AWS, Cloud, Network
maintainer:          akotlyarov@seek.com.au
version:             "0.8.7"
github:              seek-oss/serverless-haskell
license:             MIT
synopsis:            Deploying Haskell code onto AWS Lambda using Serverless
description:         Utilities to help process the events from AWS Lambda when deployed with the serverless-haskell plugin.
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-casing
  - aeson-extra
  - amazonka-core
  - amazonka-kinesis
  - amazonka-s3
  - bytestring
  - case-insensitive
  - http-types
  - iproute
  - lens
  - network
  - network-simple
  - text
  - time
  - unix
  - unordered-containers
  - aws-lambda-haskell-runtime >= 1.0.6 && < 1.1

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - serverless-haskell
      - hspec
      - hspec-discover
      - raw-strings-qq
