resolver: lts-13.0
packages:
- .
- example-project

extra-deps:
  - github: theam/aws-lambda-haskell-runtime
    commit: a4f2ab4e9de8d8f3afd1810b0ba8cf5afa2444b6

nix:
  packages:
    - zlib.dev
    - zlib.out
