// Update the list of libraries included in the AWS Lambda environment

import { spawnSync } from 'child_process';
import { writeFileSync } from 'fs-extra';
import * as path from 'path';

import * as config from './config';
import * as ld from './ld';
import * as version from './version';

const EXPORT_FILE_NAME = path.resolve(__dirname, 'AWSEnvironment.ts');

function commandOutput(cmd: string, args: string[]): string {
    const result = spawnSync(
        'docker',
        [
            'run',
            '--rm',
            '--entrypoint', cmd,
            config.DOCKER_IMAGE,
            ...args,
        ]
    );

    if (result.error || result.status && result.status > 0) {
        const stderr = result.stderr.toString().trim();
        throw new Error(`Error calling ${cmd} in the AWS image: ${stderr}`);
    }

    return result.stdout.toString().trim();
}

function getLibraries(): string[] {
    const lddOutput = commandOutput('/usr/sbin/ldconfig', [
        '-c', 'new',
        '-p'
    ]);

    const libraries = Object.keys(ld.parseLdOutput(lddOutput));

    return libraries;
}

function getGlibcVersion(): version.Version {
    const lddOutput = commandOutput('/usr/bin/ldd', ['--version']);

    const glibcVersionMatch = lddOutput.match(/((\d+.)+\d+)/);
    if (!glibcVersionMatch) {
        throw new Error(`Unexpected output from ldd: ${lddOutput}`);
    }
    const glibcVersion = version.parse(glibcVersionMatch[0]);
    return glibcVersion;
}

function main(): void {
    spawnSync('docker', ['pull', config.DOCKER_IMAGE]);

    let content = "// This file is autogenerated.\n" +
        "// Please use 'npm run updateAWSEnvironment' to update.\n";

    function addExport(name: string, value: unknown): string {
        return "export const " + name + " = " +
            JSON.stringify(value, null, 4) + ";\n";
    }

    content += addExport("libraries", getLibraries());
    content += addExport("glibcVersion", getGlibcVersion());

    writeFileSync(EXPORT_FILE_NAME, content);
}

main();
