name:                serverless-haskell-example
category:            AWS, Cloud, Network
maintainer:          akotlyarov@seek.com.au
version:             1.0.0
github:              seek-oss/serverless-haskell
license:             MIT
synopsis:            Deploying Haskell code onto AWS Lambda using Serverless
description:         Example package to demonstrate deployment of Haskell code onto AWS Lambda using Serverless

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - lens
  - serverless-haskell
  - text
  - unordered-containers

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - serverless-haskell-example
    - serverless-haskell