#!/usr/bin/env node
// Update the list of libraries included in the AWS Lambda environment

'use strict';

const {spawnSync} = require('child_process');
const fs = require('fs-extra');
const path = require('path');

const ld = require('./ld');

const LAMBDA_IMAGE = 'amazonlinux:2017.03.1.20170812';

const EXPORT_FILE_NAME = path.resolve(__dirname, 'aws_libraries.js');

function main() {
    const lddResult = spawnSync(
        'docker',
        [
            'run',
            '--rm',
            LAMBDA_IMAGE,
            'ldconfig',
            '-c', 'new',
            '-p'
        ]
    );

    if (lddResult.error || lddResult.status > 0) {
        console.log("Error calling ldconfig in the AWS image.");
        console.log(lddResult.stderr.toString('utf8').trim());
        throw "Error calling ldconfig";
    }

    const lddOutput = lddResult.stdout.toString('utf8').trim();

    const libraries = Object.keys(ld.parseLdOutput(lddOutput));

    let content = "// This file is autogenerated.\n" +
        "// Please use 'npm run update-aws-libraries' to update.\n";

    content += "module.exports = " + JSON.stringify(libraries, null, 4);

    fs.writeFileSync(EXPORT_FILE_NAME, content);
}

main();
