#!/usr/bin/env node
// Update the list of libraries included in the AWS Lambda environment

'use strict';

const {spawnSync} = require('child_process');
const fs = require('fs-extra');
const path = require('path');

const config = require('./config');
const ld = require('./ld');
const version = require('./version');

const EXPORT_FILE_NAME = path.resolve(__dirname, 'aws_environment.js');

function commandOutput(cmd, args) {
    const result = spawnSync(
        'docker',
        [
            'run',
            '--rm',
            '--entrypoint', cmd,
            config.DOCKER_IMAGE,
            ...args,
        ]
    );

    if (result.error || result.status > 0) {
        console.log("Error calling " + cmd + " in the AWS image.");
        console.log(result.stderr.toString('utf8').trim());
        throw "Error calling " + cmd;
    }

    return result.stdout.toString('utf8').trim();
}

function getLibraries() {
    const lddOutput = commandOutput('/usr/sbin/ldconfig', [
        '-c', 'new',
        '-p'
    ]);

    const libraries = Object.keys(ld.parseLdOutput(lddOutput));

    return libraries;
};

function getGlibcVersion() {
    const lddOutput = commandOutput('/usr/bin/ldd', ['--version']);

    const glibcVersionMatch = lddOutput.match(/((\d+.)+\d+)/);
    if (!glibcVersionMatch) {
        console.log("Unexpected output from ldd.")
        console.log(lddOutput);
        throw "Unexpected output from ldd.";
    }
    const glibcVersion = version.parse(glibcVersionMatch[0]);
    return glibcVersion;
}

function main() {
    let content = "// This file is autogenerated.\n" +
        "// Please use 'npm run update-aws-environment' to update.\n";

    function add_export(name, value) {
        return "module.exports." + name + " = " +
            JSON.stringify(value, null, 4) + "\n";
    }

    content += add_export("libraries", getLibraries());
    content += add_export("glibcVersion", getGlibcVersion());

    fs.writeFileSync(EXPORT_FILE_NAME, content);
}

main();
