#!/usr/bin/env node
// Update the list of libraries included in the AWS Lambda environment

'use strict';

const {spawnSync} = require('child_process');
const fs = require('fs-extra');
const path = require('path');

const LAMBDA_IMAGE = 'amazonlinux:2017.03.1.20170812';

const EXPORT_FILE_NAME = path.resolve(__dirname, 'aws_libraries.js');

function main() {
    const lddOutput = spawnSync(
        'docker',
        [
            'run',
            '--rm',
            LAMBDA_IMAGE,
            'ldconfig',
            '-c', 'new',
            '-p'
        ]
    );

    if (lddOutput.error || lddOutput.status > 0) {
        console.log("Error calling ldconfig in the AWS image.");
        console.log(lddOutput.stderr.toString('utf8').trim());
        throw "Error calling ldconfig";
    }

    const lddList = lddOutput.stdout.toString('utf8').trim().split('\n');

    const libraries = [];

    lddList.filter(ln => ln.includes('=>')).forEach(s => {
        const [name, _, libPath] = s.trim().split(' ');
        libraries.push(name);
    });

    let content = "// This file is autogenerated.\n" +
        "// Please use 'npm run update-aws-libraries' to update.\n";

    content += "module.exports = " + JSON.stringify(libraries, null, 4);

    fs.writeFileSync(EXPORT_FILE_NAME, content);
}

main();
