#!/bin/sh

set -ex

# Download and unpack the stack executable
export PATH=$HOME/.local/bin:$PATH
mkdir -p ~/.local/bin

curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

sudo apt-get update
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs

set +ex
