#!/bin/sh

set -ex

# Using compiler above sets CC to an invalid value, so unset it
unset CC

# We want to always allow newer versions of packages when building on GHC HEAD
CABALARGS=""

# Download and unpack the stack executable
export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
mkdir -p ~/.local/bin

if [ `uname` = "Darwin" ]
then
    curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
else
    curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
fi

set +ex
