#!/bin/sh

set -ex
case "$BUILD" in
    npm)
        cd serverless-plugin
        npm test
        cd -
        ;;
    integration)
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        ./integration-test/run.sh --dry-run --no-docker
        ;;
esac

set +ex
