#!/bin/sh

set -ex
case "$BUILD" in
    npm)
        npm test
        ;;
    integration)
        stack --no-terminal $ARGS --docker test --bench --no-run-benchmarks --haddock --no-haddock-deps
        ./integration-test/run.sh --dry-run
        ;;
esac

set +ex
