#!/bin/sh

set -ex
case "$BUILD" in
    stack)
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        ;;
    cabal)
        cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES

        ORIGDIR=$(pwd)
        for dir in $PACKAGES
        do
            cd $dir
            cabal check || [ "$CABALVER" == "1.16" ]
            cabal sdist
            PKGVER=$(cabal info . | awk '{print $2;exit}')
            SRC_TGZ=$PKGVER.tar.gz
            cd dist
            tar zxfv "$SRC_TGZ"
            cd "$PKGVER"
            cabal configure --enable-tests
            cabal build
            cabal test
            cd $ORIGDIR
        done
        ;;
    npm)
        cd serverless-plugin
        npm test
        cd -
        ;;
    integration)
        ./integration-test/run.sh --dry-run
        ;;
esac
