#!/usr/bin/env ruby
# Script for deploying the package via Travis CI

require 'fileutils'
require 'json'

# Release to Hackage via Stack

stack_credentials = File.expand_path('~/.stack/upload/credentials.json')
unless File.exists?(stack_credentials)
  FileUtils.mkdir_p(File.dirname(stack_credentials))

  File.open(stack_credentials, 'w') { |f|
    config = {
      :username => ENV['HACKAGE_USERNAME'],
      :password => ENV['HACKAGE_PASSWORD'],
    }
    f.write(config.to_json)
  }
end

hackage_uploaded = system('stack', 'upload', '.')
if not hackage_uploaded
  print "Failed to upload to Hackage.\n"
  exit(1)
end

# Release to NPM

npmrc = File.expand_path('~/.npmrc')
unless File.exists?(npmrc)
  File.open(npmrc, 'w') { |f|
    f.write("//registry.npmjs.org/:_authToken=#{ENV['NPM_TOKEN']}\n")
  }
  FileUtils.chmod 0600, npmrc
end

npm_uploaded = system('npm', 'publish', 'serverless-plugin')
if not npm_uploaded
  print "Failed to upload to NPM.\n"
  exit(1)
end
