#!/usr/bin/env ruby
# Script for deploying the package via Travis CI
# Use --dry-run for testing without uploading anything

require 'fileutils'
require 'json'

dry_run = ARGV[0] == '--dry-run'

stack_credentials = File.expand_path('~/.stack/upload/credentials.json')
unless File.exists?(stack_credentials)
  FileUtils.mkdir_p(File.dirname(stack_credentials))

  File.open(stack_credentials, 'w') { |f|
    config = {
      :username => ENV['HACKAGE_USERNAME'],
      :password => ENV['HACKAGE_PASSWORD'],
    }
    f.write(config.to_json)
  }
end

# Release to Hackage via Stack

if dry_run
  hackage_uploaded = system('stack', 'sdist')
else
  hackage_uploaded = system('stack', 'upload', '.')
end
if not hackage_uploaded
  print "Failed to upload to Hackage.\n"
  exit(1)
end

# Release to NPM

npmrc = File.expand_path('~/.npmrc')
unless File.exists?(npmrc)
  File.open(npmrc, 'w') { |f|
    f.write("//registry.npmjs.org/:_authToken=#{ENV['NPM_TOKEN']}\n")
  }
  FileUtils.chmod 0600, npmrc
end

Dir.chdir('serverless-plugin')
system('npm', 'install')
dry_run_arg = if dry_run then ['--dry-run'] else [] end
npm_uploaded = system('npm', 'publish', *dry_run_arg)
if not npm_uploaded
  print "Failed to upload to NPM.\n"
  exit(1)
end
