#!/bin/sh

set -ex
case "$BUILD" in
integration)
    sudo apt-get install -y jq pwgen
    stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
    ;;
npm)
    node --version
    npm --version
    cd serverless-plugin
    npm install
    cd -
    ;;
esac

set +ex
