#!/bin/sh

set -ex
case "$BUILD" in
integration)
    sudo apt-get install -y jq pwgen
    stack --no-terminal --install-ghc $ARGS --docker test --bench --only-dependencies
    ;;
npm)
    node --version
    npm --version
    npm install
    ;;
esac

set +ex
