#!/bin/sh

echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"

if [ -f configure.ac ]; then autoreconf -i; fi

set -ex
case "$BUILD" in
stack)
    # Add in extra-deps for older snapshots, as necessary
    stack --no-terminal --install-ghc $ARGS test --bench --dry-run || ( \
    stack --no-terminal $ARGS build cabal-install && \
    stack --no-terminal $ARGS solver --update-config)

    # Build the dependencies
    stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
    ;;
npm)
    sudo apt-get update
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo apt-get install -y nodejs
    node --version
    npm --version
    cd serverless-plugin
    npm install
    cd -
    ;;
integration)
    sudo apt-get update
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo apt-get install -y nodejs jq pwgen
    ;;
esac

set +ex
