name: shtest
version: 0.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- pcre-light
- serverless-haskell
- lens
- text
- unordered-containers

library:
  source-dirs: src

executables:
  bootstrap:
    source-dirs: app
    main: Main.hs
    dependencies:
      - shtest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
