service: NAME

provider:
  name: aws
  runtime: haskell

functions:
  main:
    handler: src/ThirdParty.handler

  apigw:
    handler: src/ApiGateway.handler
    events:
      - http:
          path: hello/{name}
          method: get

  subdir:
    handler: src/SubDir/SubModule.handler

  jsfunc:
    runtime: nodejs8.10
    handler: jsfunc/handler.main

plugins:
- serverless-haskell
- serverless-offline

custom:
  haskell:
    arguments:
      main:
      - one
      - two
      - --three
    # environment variables appear as strings. Index that string into a
    # dictionary with actual boolean values to get the boolean back
    docker: ${self:custom.boolean.${env:FORCE_DOCKER, "DOCKER_DEFAULT"}}
  boolean:
    true: true
    false: false
